version: "3"
networks:
  micro-net:
    driver: bridge
services:

  api_gateway:
     build: ./API-Gateways
     network:
       - micro-network
      ports:
        - "3005:3005"
     volumes:
      - ./API-Gateway:/developer/nodejs/api-gateway
       - api-gateway-node-modules:/developer/nodejs/api-gateway/node_modules

   booking_service:
    build: ./Booking-Service
    network:
    - micro-network
    ports:
     - "4000:4000"
    volumes:
    - ./API-Gateway:/developer/nodejs/booking
    - booking-service-node-modules:/developer/nodejs/booking/node_modules

   notification_service:
    build: ./notification-Service
    network:
    - micro-network
    ports:
     - "3008:3008"
    volumes:
    - ./notification_service:/developer/nodejs/noti
    - noti-service-node-modules:/developer/nodejs/noti/node_modules

   project2:
     build: ./project2
     network:
      - micro-network
     ports:
      - "3000:3000"
     volumes:
     - ./project2:/developer/nodejs/flightsearch
     -  flight-service-node-modules:/developer/nodejs/noti/node_modules
 

