services:
  - type: web
    name: auth_service
    env: docker
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: ""
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: booking_service
    env: docker
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: ""
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 8001

  - type: web
    name: delivery_service
    env: docker
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: ""
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 8002

  - type: web
    name: flight_search
    env: docker
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: ""
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 8003
