services:
  - type: web
    name: auth_service
    env: docker
    plan: free
    region: oregon
    autoDeploy: true
    dockerContext: ./Auth_service
    dockerfilePath: ./Auth_service/Dockerfile

  - type: web
    name: booking_service
    env: docker
    plan: free
    region: oregon
    autoDeploy: true
    dockerContext: ./Booking-Service
    dockerfilePath: ./Booking-Service/Dockerfile

  - type: web
    name: delivery_service
    env: docker
    plan: free
    region: oregon
    autoDeploy: true
    dockerContext: ./notification_service
    dockerfilePath: ./notification_service/Dockerfile

  - type: web
    name: flight_search
    env: docker
    plan: free
    region: oregon
    autoDeploy: true
    dockerContext: ./flight-Search
    dockerfilePath: ./flight-Search/Dockerfile

  - type: web
    name: docs
    env: docker
    plan: free
    region: oregon
    autoDeploy: true
    dockerContext: ./docs
    dockerfilePath: ./docs/Dockerfile
