services:
  - type: web
    name: auth-service
    env: docker
    dockerContext: ./Auth_service
    dockerfilePath: ./Auth_service/Dockerfile
    plan: free
    autoDeploy: true
    region: oregon

  - type: web
    name: booking-service
    env: docker
    dockerContext: ./Booking-Service
    dockerfilePath: ./Booking-Service/Dockerfile
    plan: free
    autoDeploy: true
    region: oregon

  - type: web
    name: notification-service
    env: docker
    dockerContext: ./notification_service
    dockerfilePath: ./notification_service/Dockerfile
    plan: free
    autoDeploy: true
    region: oregon
    envVars:
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672

  - type: web
    name: flight-search
    env: docker
    dockerContext: ./flight-Search
    dockerfilePath: ./flight-Search/Dockerfile
    plan: free
    autoDeploy: true
    region: oregon

  - type: worker
    name: rabbitmq
    env: docker
    image: rabbitmq:3-management
    plan: free
    autoDeploy: true
    region: oregon
