FROM node

WORKDIR /developer/nodejs/noti

ENV NODE_ENV=development

COPY . .

ENV PORT=3000

RUN npm ci

# Run cd src && npx sequelize db:create
# Run cd src && npx sequelize db:migrate


CMD ["npm","run","dev"]