FROM node 

WORKDIR /developer/nodejs/booking

ENV NODE_ENV=development

COPY . .

RUN npm ci

ENV PORT=4000

# Run cd src && npx sequelize db:create
# Run cd src && npx sequelize db:migrate

CMD ["npm","run","dev"]